theme: jekyll-theme-leap-day
title: Assertions for Result
description: Fluent assertions for Result objects
current_version: 1.1.0.0
show_downloads: true
logo: https://dev.leakyabstractions.com/result/result-banner.png
exclude:
  - gradle
  - result-assertj
